---
- name: Apply ACL
  hosts: demo-win
  gather_facts: no
  become_method: runas
  become: yes
  tasks:
  - name: Remove Everyone Group in C Drives
    win_command: icacls C:\ /remove Everyone
    args:
      executable: cmd

  - name: Remove Everyone Group in D Drives
    win_command: icacls D:\ /remove Everyone
    args:
      executable: cmd

  - name: Remove Users Group in C Drives
    win_command: icacls C:\ /remove Users
    args:
      executable: cmd

  - name: Remove Users Group in D Drives
    win_command: icacls D:\ /remove Users
    args:
      executable: cmd
