---
- name: ACL Permission
  hosts: demo-win
  gather_facts: no
  become_method: runas
  become: yes
  tasks:
  - name: Remove Everyone Group in C Drives
    win_command: icacls C:\ /remove Everyone
    args:
      executable: cmd
    




