---
- name: Registry change
  hosts: demo-win
  gather_facts: no
  become_method: runas
  become: yes
  tasks:
  - name: Add or update registry, with dword entry '0', and containing 1337 as the decimal value
    win_regedit:
      path: HKLM:\System\CurrentControlSet\Services\LanmanServer\Parameters
      name: AutoShareServer
      data: 00000000
      type: dword

  