---
- name: Add DEVELOPMENT\DBA team to local admin group
  hosts: provision-dev
  tasks:
  - name: Executing Command
    win_command: powershell -command "& { ([adsi]'WinNT://./Administrators,group').Add('WinNT://DEVELOPMENT/IT DBA Team'); }"
    args:
      executable: cmd