---
- name: Rename Administrator to DBSadmin
  hosts: provision-dev
  tasks:
  - name: Executing Command
    win_command: wmic useraccount where name='Administrator' rename DBSadmin
    args:
      executable: cmd